import Header from "@/components/header/Header";
import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";

const roboto_serif = Roboto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <head>
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={`bg-white ${roboto_serif.className}`}>
        {/* <InfoHeader /> */}
        <Header />
        {children}

        <div className="z-10 h-[200vh] w-full bg-white" />
      </body>
    </html>
  );
}
